/**
 * dump-live-configs.ts — emit current live algo configs in the same
 * shape as scripts/multi-algo-backtest.ts DEFAULT_CONFIGS, so harness
 * runs stay live-faithful without hand-maintaining the constant.
 *
 * Per `feedback_harness_vs_live_drift.md`: DEFAULT_CONFIGS hand-
 * maintained, drifts silently when live configs change. Caught
 * 2026-05-08 (30m=v3 in harness vs v5 live, 15m lookback 8 vs 12).
 * Drift confirmed again 2026-05-18 (30m still v3 in harness vs v5
 * live; both algos risk 1.0 in harness vs 0.75 live).
 *
 * Output:
 *   1. A typescript array literal in AlgoConfig format — copy/paste
 *      replacement for DEFAULT_CONFIGS
 *   2. A diff vs the in-tree DEFAULT_CONFIGS so drift is obvious
 *
 * Usage:
 *   pnpm dlx tsx scripts/dump-live-configs.ts
 *
 * Run before every "live-faithful backtest" of multi-algo-backtest.ts.
 * If output shows drift vs DEFAULT_CONFIGS, either update the constant
 * or pass the live config inline via env override before running.
 */
import { readFileSync } from "fs";
import { createClient } from "@supabase/supabase-js";

{
  try {
    const raw = readFileSync(".env.local", "utf8");
    for (const line of raw.split(/\r?\n/)) {
      const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
      if (!m) continue;
      const [, k, v] = m;
      if (!process.env[k]) process.env[k] = v.replace(/^['"]|['"]$/g, "");
    }
  } catch {
    /* ignore */
  }
}

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!supabaseUrl || !serviceKey) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}
const supabase = createClient(supabaseUrl, serviceKey, {
  auth: { persistSession: false },
});

interface LiveAlgo {
  id: string;
  name: string;
  rules: Record<string, unknown>;
}

function shortLabel(name: string): string {
  // "Gold Swing 4h" → "v1_4h_swing" (matches existing DEFAULT_CONFIGS naming
  // intent: <prompt>_<tf>_<kind>). Fall back to the name itself for new
  // algos that don't fit the pattern — operator can rename if needed.
  const lower = name.toLowerCase();
  if (/swing.*4h|4h.*swing/.test(lower)) return "v1_4h_swing";
  if (/intraday.*30m|30m.*intraday/.test(lower)) return "intraday_30m";
  if (/intraday.*15m|15m.*intraday/.test(lower)) return "intraday_15m";
  return name.replace(/\s+/g, "_").toLowerCase();
}

async function main(): Promise<void> {
  const { data: algos, error } = await supabase
    .from("algorithms")
    .select("id, name, rules")
    .eq("status", "active")
    .eq("live_trading_enabled", true)
    .order("name");
  if (error) throw error;
  if (!algos || algos.length === 0) {
    console.log("No active+live algos found.");
    return;
  }

  console.log("// Generated by scripts/dump-live-configs.ts");
  console.log(`// Snapshot @ ${new Date().toISOString()}`);
  console.log(`// Source: Supabase algorithms table, status=active + live_trading_enabled=true`);
  console.log("export const DEFAULT_CONFIGS: AlgoConfig[] = [");

  for (const a of algos as LiveAlgo[]) {
    const r = a.rules;
    const tf = r.timeframe as string | undefined;
    const llm = r.llm_trader as Record<string, unknown> | undefined;
    const sl = r.stop_loss as Record<string, unknown> | undefined;
    const tp = r.take_profit as Record<string, unknown> | undefined;
    const sizing = r.position_sizing as Record<string, unknown> | undefined;
    const maxPositions = r.max_positions as number | undefined;

    const label = shortLabel(a.name);
    const promptVersion = (llm?.prompt_version as string | undefined) ?? "v2";
    const risk = (sizing?.value as number | undefined) ?? 0;

    console.log(`  {`);
    console.log(`    algoId: "${label}",`);
    console.log(`    label: "${a.name}",`);
    console.log(`    timeframe: "${tf}",`);
    console.log(`    promptVersion: "${promptVersion}",`);
    console.log(`    riskPerTradePct: ${risk},`);
    console.log(`    maxPositions: ${maxPositions ?? 1},`);
    if (sl) {
      console.log(`    sl: ${JSON.stringify(sl)},`);
    }
    if (tp) {
      console.log(`    tp: ${JSON.stringify(tp)},`);
    }
    console.log(`    // Live algoId in Supabase: ${a.id}`);
    console.log(`  },`);
  }
  console.log("];");

  console.log("");
  console.log("// ---");
  console.log("// DRIFT CHECK — compare the above to DEFAULT_CONFIGS in");
  console.log("// scripts/multi-algo-backtest.ts. If anything differs, the");
  console.log("// harness is producing live-divergent results. Per");
  console.log("// feedback_harness_vs_live_drift.md, this is a known recurring");
  console.log("// failure mode — caught 2026-05-08, 2026-05-18.");
  console.log("//");
  console.log("// Quick eyeball check after copying:");
  console.log("//   diff <(awk '/DEFAULT_CONFIGS/,/^]/' scripts/multi-algo-backtest.ts | head -25) \\");
  console.log("//        <(pnpm dlx tsx scripts/dump-live-configs.ts 2>/dev/null | head -25)");
}

main().catch((err) => {
  console.error("dump-live-configs.ts failed:", err);
  process.exit(1);
});
